# Generated by Django 5.0.6 on 2024-05-28 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='media/advertising/image')),
                ('video', models.FileField(null=True, upload_to='media/advertising/video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBirthdays',
            fields=[
                ('birthday_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('age', models.IntegerField()),
                ('friends', models.TextField()),
                ('close_friends', models.TextField()),
                ('wishlist', models.TextField()),
                ('phone_number', models.CharField(max_length=13)),
                ('image', models.ImageField(null=True, upload_to='media/birthday/')),
                ('birthday', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('telegram_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.users', to_field='telegram_id')),
            ],
        ),
    ]
