# Generated by Django 5.0.6 on 2024-05-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
