# Generated by Django 5.0.6 on 2024-05-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_advertisement_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbirthdays',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
