# Generated by Django 5.0.6 on 2024-05-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_userbirthdays_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.TextField(unique=True),
        ),
    ]
