# Generated by Django 5.0.6 on 2024-05-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_alter_users_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/advertising/image'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/advertising/video'),
        ),
    ]
