# Generated by Django 5.0.6 on 2024-05-28 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_userimage_remove_userbirthdays_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbirthdays',
            name='images',
        ),
        migrations.CreateModel(
            name='UserBirthdayImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/birthday/')),
                ('user_birthday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.userbirthdays')),
            ],
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
