# Generated by Django 5.0.6 on 2024-05-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbirthdays',
            name='wishlist',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
